name: CI - Build and push

on:
  push:
    tags:
      - "*"

jobs:
  build-and-push-camyo:
    name: Build and push Camyo
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Log in to the Container registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Get the tag
        id: get_tag
        run: echo "tag=${{ github.ref_name }}" >> $GITHUB_OUTPUT
      - name: Build
        uses: docker/build-push-action@v3
        with:
          context: .
          file: Dockerfile
          push: true
          tags: ghcr.io/${{ github.actor }}/camyo:${{ steps.get_tag.outputs.tag }} , ghcr.io/${{ github.actor }}/camyo:latest
